using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Chibi sprite sheets generated by tools/sprites/chibi.py: 3 columns (idle, step A, step B) × 4 rows
/// (down, left, right, up), frame size = sheet size / (3, 4) (24×32 px), loaded from Resources/Sprites.
/// </summary>
public static class Chibi
{
    public const int PixelsPerUnit = 16;
    static readonly Dictionary<string, Sprite[]> Cache = new();

    /// <summary>Frames indexed dir * 3 + pose, or null when the sheet does not exist.</summary>
    public static Sprite[] Load(string sheet)
    {
        if (string.IsNullOrEmpty(sheet)) return null;
        if (Cache.TryGetValue(sheet, out var frames)) return frames;
        var tex = Resources.Load<Texture2D>("Sprites/" + sheet);
        if (tex != null)
        {
            tex.filterMode = FilterMode.Point;
            frames = new Sprite[12];
            int fw = tex.width / 3, fh = tex.height / 4;
            for (int dir = 0; dir < 4; dir++)
            for (int pose = 0; pose < 3; pose++)
            {
                // Texture rows start at the bottom: row 0 of the sheet (down) is the top one.
                var rect = new Rect(pose * fw, tex.height - (dir + 1) * fh, fw, fh);
                frames[dir * 3 + pose] = Sprite.Create(tex, rect, new Vector2(0.5f, 0.05f), PixelsPerUnit);
            }
        }
        Cache[sheet] = frames;
        return frames;
    }

    static readonly Dictionary<string, Sprite> Singles = new();

    /// <summary>A whole texture as one sprite with the pivot at the bottom centre (buildings).</summary>
    public static Sprite LoadSingle(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        if (Singles.TryGetValue(name, out var s)) return s;
        var tex = Resources.Load<Texture2D>("Sprites/" + name);
        if (tex != null)
        {
            tex.filterMode = FilterMode.Point;
            s = Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), new Vector2(0.5f, 0f), PixelsPerUnit);
        }
        Singles[name] = s;
        return s;
    }

    /// <summary>Sorting order for a map row: lower on the map is drawn in front.</summary>
    public static int OrderForY(float worldY) => 100 + Mathf.RoundToInt(-worldY * 4f) * 8;

    /// <summary>0 down, 1 left, 2 right, 3 up from a world-space movement.</summary>
    public static int Direction(Vector3 delta, int current)
    {
        if (delta.sqrMagnitude < 0.0001f) return current;
        if (Mathf.Abs(delta.x) > Mathf.Abs(delta.y)) return delta.x < 0 ? 1 : 2;
        return delta.y > 0 ? 3 : 0;
    }
}
