using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Chibi sprite sheets generated by tools/sprites/chibi.py: 3 columns (idle, step A, step B) × 4 rows
/// (down, left, right, up), 16×20 px per frame, loaded from Resources/Sprites.
/// </summary>
public static class Chibi
{
    public const int FrameW = 16, FrameH = 20, PixelsPerUnit = 16;
    static readonly Dictionary<string, Sprite[]> Cache = new();

    /// <summary>Frames indexed dir * 3 + pose, or null when the sheet does not exist.</summary>
    public static Sprite[] Load(string sheet)
    {
        if (string.IsNullOrEmpty(sheet)) return null;
        if (Cache.TryGetValue(sheet, out var frames)) return frames;
        var tex = Resources.Load<Texture2D>("Sprites/" + sheet);
        if (tex != null)
        {
            tex.filterMode = FilterMode.Point;
            frames = new Sprite[12];
            for (int dir = 0; dir < 4; dir++)
            for (int pose = 0; pose < 3; pose++)
            {
                // Texture rows start at the bottom: row 0 of the sheet (down) is the top one.
                var rect = new Rect(pose * FrameW, tex.height - (dir + 1) * FrameH, FrameW, FrameH);
                frames[dir * 3 + pose] = Sprite.Create(tex, rect, new Vector2(0.5f, 0.05f), PixelsPerUnit);
            }
        }
        Cache[sheet] = frames;
        return frames;
    }

    /// <summary>0 down, 1 left, 2 right, 3 up from a world-space movement.</summary>
    public static int Direction(Vector3 delta, int current)
    {
        if (delta.sqrMagnitude < 0.0001f) return current;
        if (Mathf.Abs(delta.x) > Mathf.Abs(delta.y)) return delta.x < 0 ? 1 : 2;
        return delta.y > 0 ? 3 : 0;
    }
}
